# Generated by Django 3.2.14 on 2022-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predict', models.CharField(max_length=70)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='uploads')),
                ('answer', models.CharField(max_length=70)),
            ],
        ),
    ]
