# Generated by Django 3.2.14 on 2022-08-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='predict',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
