# Generated by Django 3.2.14 on 2022-08-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220806_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('predict', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='uploads')),
            ],
        ),
    ]
