# Generated by Django 3.2.14 on 2022-08-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_newproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
